apiVersion: v1
kind: ServiceAccount
metadata:
  name: cat-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cat-controller-role
rules:
- apiGroups:
  - example.cats.io
  resources:
  - cats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.cats.io
  resources:
  - cats/finalizers
  verbs:
  - update
- apiGroups:
  - example.cats.io
  resources:
  - cats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cat-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cat-controller-role
subjects:
- kind: ServiceAccount
  name: cat-controller
